### ISSUE TITLE
Update data files

### ISSUE THREAD

**Issue by oeyvind-bjoeru** [jackweinbender/zeichenliste#18]
- [x] Get the 192 signs in our spreadsheet into json.

**Comment by jackweinbender** [comment]
We should put together a build file to pull down all of this.

**Comment by oeyvind-bjoeru** [comment]
I have written two scripts that pull the data from the spreadsheet.
One makes Key(Borger#)–Value(whole sign, including Borger#): idIndex.json.
The other keys all values and sign list numbers to a Borger number: lookupBorger.json. I also added the bare values with a 1 at the end in the lookupBorger.json.

Was that something like what we were looking for?

**Comment by oeyvind-bjoeru** [comment]
No, the lookupBorger.json is not quite right.
I made a dict of Borger# linked to a list of relevant values, but then reversed it, and it became a one-to-one which presumes precise lookup. I will redo it.

**Comment by jackweinbender** [comment]
It's a good start, though. I made an attempt, too, but haven't quite nailed it down. [This is what I've been doing](https://github.com/jackweinbender/zeichenliste/blob/10b3557c80a82f11c7a118a5ce31e3bd659349b7/build.py#L1). It's mostly the first list that you started on, but now it'll pull from that sheet whenever we run it.
