### ISSUE TITLE
OAkk values

### ISSUE THREAD

**Issue by oeyvind-bjoeru** [jackweinbender/zeichenliste#52]
Make list (no freqs) of values used in OAkk and display.

**Comment by jackweinbender** [comment]
THe list has been added to `dev`, but we still need to display it. (this was already done, but we rolled it back, so copy-paste from old commits)

**Comment by jackweinbender** [comment]
There aren't any real frequencies in this file, so we shouldn't display "frequencies" but, we should list values.
