### ISSUE TITLE
Stats strategy

### ISSUE THREAD

**Issue by jackweinbender** [jackweinbender/zeichenliste#6]
We need to come up with a strategy for organizing and displaying stats data that we are pulling from Oracc and other sources.

**Comment by jackweinbender** [comment]
The stats files look good, but we need to change one thing about them. Ideally they will be formatted using the Borger number as the Key, and all the info as the value. So, Instead of:
```
    "ANŠE": {
        "borger": "353",
        "freq": "96",
        "type": "Determinative"
```
We'd prefer
```
    "353": {
        "name": "ANŠE", 
        "freq": "96",
        "type": "Determinative"
```
so we can do the lookups in constant time.

**Comment by oeyvind-bjoeru** [comment]
Yeah, but I don't know how to do that, it's many–to–one. There would be several with the same key. That is why I thought we would scan through every key and see if it has a borger number that matches.

```def link_value_to_sign(freq_list, sign)
	for each in freq_list.keys():
		if 'borger' in freq_list[each].keys():
			if freq_list[each]['borger'] == sign:
				#whatever
```
Alternatively we could hang several values with their info under one main node, which is essentially the outcome of the above procedure and what you want, but it's potentially a little more hassle as we add more signs to our database.

In the end, a two-line script could take care of it. I have all the code for turning the different data sets into this format, and I think the same quick procedure could be applied to all of them, but it would look like

```
	"353": {
		"ANŠE": {
			"freq": "96",
			"type": "Determinative"}
		"an20": {
			"freq": "not really",
			"type": "invented"}
		etc.
```

**Comment by jackweinbender** [comment]
Ah, I see. For the sake of performance, the second option is better, for sure, since It means we dont' have to iterate through the whole list on every lookup. I think it may be slightly more idiomatic to use a list for the VALUE. Like:

```
"353": [  // <- List
  { "name": "ANŠE", 
    "freq": "96",
    "type": "Determinative" }
  { "name": "an20":,
    "freq": "not really",
    "type": "invented" } ]
```

**Comment by oeyvind-bjoeru** [comment]
I think the files are in the right format now. Helpless as I am, I wasn't able to delete the previous files with the same names, though.

**Comment by oeyvind-bjoeru** [comment]
The files include only the Borger numbers in our set of 192 signs.
And each dialect freq list only includes the values actually attested in that data set.
The frequencies are absolute values out of a total found in "About frequency lists.txt".

**Comment by oeyvind-bjoeru** [comment]
For the display, it might make sense to list all values as we have been, and then do the frequencies in a separate section. Since so many values will be without freq info, and the same values will not have a freq in all of the dialects, they might be listed individually:

![image](https://user-images.githubusercontent.com/47754479/54155719-c400d600-4412-11e9-96b4-b1056b918943.png)

**Comment by oeyvind-bjoeru** [comment]
I think it makes sense to combine the numbers to get a total for the sign as such in each dialect (OB 0.41%, and NA 0.55%) above.

For the individual values, I wonder if is just as useful to just list the absolute frequency, or do percentage of the sign, cause you end up with a lot of tiny percentages.

**Comment by jackweinbender** [comment]
I've added the stats section (I'll add a section header I think). I went with absolute frquencies, which I think is most useful. It gives an idea of how big the sample size is and it's simple math if anyone wants to use percents (maybe I should do totals though?).

The display looks close to what you've suggested. As a matter of geometry I broke it into two row, and it collapses into a single column under 600px.

I think I'd like to (maybe?) ditch the "type" and/or incorporate a bar-chart, which I think would be a nice visual.

![image](https://user-images.githubusercontent.com/1544859/54172957-eb28c900-444d-11e9-90d6-3a64d3fc850b.png)

**Comment by jackweinbender** [comment]
I've added some bar-charts and took away the type:

I'm not 100% sure what the difference is between E2 and e2, but as long as there IS a difference, and that Assyriologists know what it is, I'm cool with it.

![image](https://user-images.githubusercontent.com/1544859/54178132-b96e2d00-4462-11e9-950e-ff968de7b114.png)

**Comment by jackweinbender** [comment]
I think we've got the stats stuff taken care of for now, so I'm going to close this issue.
